# Generated by Django 6.0.1 on 2026-01-08 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('modulo', models.CharField(choices=[('FINANCEIRO', 'Financeiro'), ('ESTUDOS', 'Estudos'), ('SAUDE', 'Saúde'), ('TRABALHO', 'Trabalho'), ('HOBBIES', 'Hobbies'), ('AUTOCUIDADO', 'Autocuidado')], max_length=50)),
                ('tipo', models.CharField(choices=[('CHECKLIST', 'Checklist (Sim/Não)'), ('PROGRESSO', 'Progresso (Acumulativo)')], default='CHECKLIST', max_length=50)),
                ('frequencia', models.CharField(choices=[('UNICA', 'Única'), ('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], default='UNICA', max_length=50)),
                ('dias_especificos', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('arquivado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MetaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('realizado', models.BooleanField(default=False)),
                ('valor_meta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_atingido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_metas', to='objetivos.objetivomacro')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
