# Generated by Django 6.0.1 on 2026-01-08 11:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cor', models.CharField(default='#268b9b', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PDF', 'Arquivo PDF'), ('LINK', 'Link')], max_length=10)),
                ('url', models.URLField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='estudos_pdfs/')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='estudos.assunto')),
            ],
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_revisao', models.DateTimeField(default=django.utils.timezone.now)),
                ('concluida', models.BooleanField(default=False)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='estudos.assunto')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('horas_totais', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('validado_no_calendario', models.BooleanField(default=False)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='estudos.assunto')),
            ],
        ),
    ]
